### ISSUE TITLE
Bedrock Support

### ISSUE THREAD

**Issue by BobtheBob123456** [Filocava99/CavaAntiCheat#1]
Hi Guys,
First of, I would like to say that this is an impressive plugin. The only problem I have is the fact that it doesn't say anything about using this olugin with GeyserMC/Floodgate.

Could you please add Bedrock players support?

Thanks,

**Comment by Filocava99** [comment]
Hello! I am glad you have found the project interesting. I never thought about adding support for BE since there aren't any hack-clients for it. I could probably hook into Floodgate's api and ignore the checks for BE players. I will update the [Floodgate wiki](https://wiki.geysermc.org/geyser/anticheat-compatibility/) when work's done.

**Comment by Filocava99** [comment]
[CavaAntiCheatServer-1.1.0.zip](https://github.com/Filocava99/CavaAntiCheat/files/9035158/CavaAntiCheatServer-1.1.0.zip)

Try this snapshot. If it works I will upload it on Spigot

**Comment by BobtheBob123456** [comment]
Thanks. Also two questions. One, does this snapshot just ignore bedrock players, or does it check them. 

Two, while bedrock players cannot use mods they can still use resource packs and have something else called addons. What if there was a way to whitelist bedrock resource packs, and prevent players who have un-whitelisted addons/packs from joining?

I don't know if this is possible. But if it isn't, then it is fine.

**Comment by Filocava99** [comment]
That snapshots simply ignore BE players.
Unfortunately there isn't an API to verify which addons the player is using. Minecraft BE modding is very limited due to cross-platform compatibility.

If it works please let me know so I can upload it on Spigot.

**Comment by BobtheBob123456** [comment]
Got it. Also, for the minecraft SHA-156, do I have to change it. If so what do I change it to?

**Comment by Filocava99** [comment]
Im not sure what you mean.

Let's suppose you want Java players to join your server using minecraft
1.19. In that scenario you have to find the minecraft 1.19 jar and compute
its hash. You can find the jar in .minecraft/versions/1.19/1.19.jar

**Comment by BobtheBob123456** [comment]
But isn't that included since the plugin is for 1.19

**Comment by Filocava99** [comment]
No because you might want to use a customized Minecraft jar. The config has
been made like that to make it highly versatile

**Comment by Filocava99** [comment]
I suppose I can add in the config.yml the hashes of the default Minecraft versions jars and you can uncomment the one that you need.
Did you test the snapshot?

**Comment by Filocava99** [comment]
@BobtheBob123456 news? Otherwise I will have to mark the issue has resolved

**Comment by BobtheBob123456** [comment]
It didn't work. It said, 'unable to verify the presence of the client anti cheat'

Also, what is the purpose of the cava anti cheat client and is it required to play on the server.

Thanks,

**Comment by Filocava99** [comment]
Umh weird. Can you paste the startup log and the logs of when you attempted to join the server? Maybe there is some kind of exception. Are you sure you have installed Floodgate for spigot?

The CavaAntiCheat-client is a Forge mod that must be installed on Minecraft Java edition. It's required to detect blacklisted mods, texture packs or tampering of the original jars.

**Comment by BobtheBob123456** [comment]
Once again, it didn't work. Here is a screenshot of the logs. Also, I definitely have Floodgate installed.

[Screenshot_20220707-084323_Chrome](https://user-images.githubusercontent.com/101293758/177777003-6da90401-e4ef-498b-8abe-4f45257b52b5.jpg)

**Comment by BobtheBob123456** [comment]
Also, could you create a version of the client that works on Fabric? And does whitelisting resource packs require a SHA256 as well.

**Comment by Filocava99** [comment]
Yes the resource pack, as also stated in the installation guide, requires the SHA256 as well. No I won't develop a Fabric mod I'm sorry.
I will close the issue since in the logs you have pasted I can't see what is your setup.
> Can you paste **the startup log** and the logs of when you attempted to join the server?

In such logs I can see the Spigot/Paper version you are using and if you have installed GayserMC/Floodgate
If you provide them, this time by pasting text and not an image, I might reopen the issue.

**Comment by BobtheBob123456** [comment]
Oh. Here are the setup logs. As you can see, I do have Floodgate installed.
[Screenshot_20220708-102324_Chrome](https://user-images.githubusercontent.com/101293758/178011876-df78cf6a-5419-4a99-81ab-7d25ca24bc83.jpg)

**Comment by BobtheBob123456** [comment]
Also, I use Spigot 1.19

**Comment by Filocava99** [comment]
I'm sorry but I can't help you if you keep posting screenshots. I need the entire startup log, that's it. _E.g. is CavaAntiCheat getting enabled after Floodgate? Without the startup log I can't tell._

**Comment by BobtheBob123456** [comment]
Oh, ok. Here is the latest log that I have.
[latest.log](https://github.com/Filocava99/CavaAntiCheat/files/9073094/latest.log)
