### ISSUE TITLE
Bedrock Support (Continued)

### ISSUE THREAD

**Issue by BobtheBob123456** [Filocava99/CavaAntiCheat#2]
Hi Guys,
So I finally figured out how to get my server logs (Don't ask how I didn't know that) and they are ready to view. Could you please look at them to see what is wrong, and why it is not allowing bedrock players to join?

Thanks,

[2022-07-07-1.log.gz](https://github.com/Filocava99/CavaAntiCheat/files/9078226/2022-07-07-1.log.gz)

**Comment by BobtheBob123456** [comment]
Hi Guys,
As you asked in the previous issue, I have the logs of me trying to join so that you can see, what version of MC my server runs and if I have floodgate installed.

I know it took me a while to get the logs, but now that I have them, could you please look at them and see what is wrong?

Thanks,

**Comment by Filocava99** [comment]
[CavaAntiCheatServer-1.1.0.zip](https://github.com/Filocava99/CavaAntiCheat/files/9111293/CavaAntiCheatServer-1.1.0.zip)

Try this debug version please. Then paste the full log so I can find what is not working

**Comment by BobtheBob123456** [comment]
Ok, so I tried the debugversion, and I think the issue is that the anti cheat cant detect that floodgate is on the server, even though it is.

https://www.dropbox.com/s/s8f5mmbghk8b28v/2022-07-15-4.log?dl=0

**Comment by Filocava99** [comment]
I have found the issue. I was calling the `isPluginEnable()` method but floodgate is getting enabled after the anticheat, thus returning always false.

**Comment by Filocava99** [comment]
Try this version, it should work:
[CavaAntiCheatServer.zip](https://github.com/Filocava99/CavaAntiCheat/files/9120924/CavaAntiCheatServer.zip)

**Comment by BobtheBob123456** [comment]
Still doesn't work. This time, it didn't detect that I was a Floodgate player.

Here is log
https://www.dropbox.com/s/3k2pkcqie9ec0s6/latest.log.txt?dl=0

**Comment by Filocava99** [comment]
That's actually very weird because the API of floodgate is pretty straightforward. `FloodgateAPI.getInstance().isFloodgatePlayer(uuid)` should return true if you actually joined the server using Minecraft Bedrock edition.
I have coded a workaround that is not efficient since it iterate the whole list of bedrock players but it should work.
[CavaAntiCheatServer-1.1.0.zip](https://github.com/Filocava99/CavaAntiCheat/files/9121150/CavaAntiCheatServer-1.1.0.zip)

**Comment by BobtheBob123456** [comment]
For some reason, it still doesn't detect that I am a floodgate player. Here is the log

https://www.dropbox.com/s/3k2pkcqie9ec0s6/latest.log.txt?dl=0

**Comment by Filocava99** [comment]
Are you connecting with Minecraft Bedrock edition right?

**Comment by BobtheBob123456** [comment]
Yes. I play PE. Here is my loading screen as proof. Maybe you could try testing the plugin on Bedrock using your own account (if you have one).

![Screenshot_20220716-081855_Minecraft](https://user-images.githubusercontent.com/101293758/179354652-395bac1e-c879-4fb0-9edf-9890657aa563.jpg)

**Comment by BobtheBob123456** [comment]
Yes, here is my loading screen as proof. Maybe you could try the plugin with your bedrock account if you have one.
![Screenshot_20220716-082244_Minecraft](https://user-images.githubusercontent.com/101293758/179354748-22b67ba7-1e57-4af0-833a-b93ac376da7d.jpg)

**Comment by Filocava99** [comment]
I am opening an issue on the floodgate repo cause at this point I think it's a bug with their API

**Comment by Filocava99** [comment]
Dude you are using Craftbukkit instead of Spigot...

**Comment by Filocava99** [comment]
https://github.com/GeyserMC/Floodgate/issues/336

**Comment by BobtheBob123456** [comment]
Oh, ok. But here I says I am using spigot 1.19.
![Screenshot_20220716-084707_Chrome](https://user-images.githubusercontent.com/101293758/179355588-38ed7de6-52fc-4550-ad9c-d018b2ec522d.jpg)

**Comment by BobtheBob123456** [comment]
I don't get why it is running craftbukkit when it says my server is spigot 1.19

**Comment by Filocava99** [comment]
Nah don't worry it's fine. As you can see your server version is implementing the SpigotAPI, ergo you are using Spigot.
Long story short: Spigot is a patched version of CraftBukkit with lots of improvements. That's why you see CraftBukkit.

**Comment by Filocava99** [comment]
[CavaAntiCheatServer-1.1.0.zip](https://github.com/Filocava99/CavaAntiCheat/files/9135438/CavaAntiCheatServer-1.1.0.zip)
Try this version. It probably won't work but we have to try.

**Comment by BobtheBob123456** [comment]
Your right. It didn't work.
https://www.dropbox.com/s/3k2pkcqie9ec0s6/latest.log.txt?dl=0

**Comment by BobtheBob123456** [comment]
Hey man. How is the anti-cheat coming along?

**Comment by Filocava99** [comment]
Apparently the anticheat works. The developers of floodgate tested it and didn't have any troubles joining with BE client.
I guess you have misconfigured something on your server. Check if you have installed geyserMC and floodgate correctly. Be sure to be using the latest verions of those plugins and of Spigot 1.19.

**Comment by Filocava99** [comment]
Since there isn't a bug I will close the issue. For further support use discord or Spigot. Github is only for discussing bugs or enhancements

**Comment by BobtheBob123456** [comment]
What discord?

**Comment by Filocava99** [comment]
The [discord url](https://discord.com/invite/FDC3ysqtZk) is in the Spigot page of the plugin. However your attitude was not respectful at all. Instead of rating the plugin with 3 stars for an issue that is not related with the plugin but for a problem with your server setup, you should have used the discussion section on spigot or the discord server. Please stop using Github for support, it has to be used only for bug tracking and that's not the case.

**Comment by BobtheBob123456** [comment]
Hey Man,
First of, I would like to say that I am sorry for what I did. I shouldn't have written that review, and I truly am sorry.

You see, back in the day I had a moderately sized server. It was doing OK, but there were no anti-cheats installed.

As such, a group of players logged on, and using hacks, completely  destroyed the server. Over half the players we had left, and we had to switch to another server.

Since then I have been in a constant state of frustration, and stress, working to keep the server alive, which only increased after the anti-cheat wasn't working for me, and I guess that anger spilled over.

Still, I understand what I did was wrong and disrepctful, and I truly am sorry. You have been a great help, explaining your plugin to me and taking your time to help, and I haven't returned the favor.

I know you probably dont want to talk to me, and I deserve that, but could you please help me out? This time, I will use the Discussion Part of the spigot page.

Your plugin is great, and once again, I apologize for my disrespect.

Thanks For All Your Help,
Bob

**Comment by Filocava99** [comment]
I always provide support for my plugins, no matter what. But please delete that review. See you on Spigot
