### ISSUE TITLE
Hope to add more version support

### ISSUE THREAD

**Issue by misss520** [Filocava99/CavaAntiCheat#3]
I hope to add more version support, such as 1.8.8, the supported version is too small, it is difficult to use on a large scale

**Comment by Filocava99** [comment]
I'm sorry but only future versions of Minecraft will be supported. Minecraft 1.8.8 is very old and based on a different version of Java. It also requires to rewrite entirely the Forge mod since the APIs are totally different.

**Comment by Leandroide17** [comment]
Hii, and can you add support for version 1.18.2 ?
