### ISSUE TITLE
Bypass permissions [Enhancement]

### ISSUE THREAD

**Issue by BartosB13** [Filocava99/CavaAntiCheat#7]
Would there be a chance to add a parmision:

1. Full bypass from client control
2. Partial bypass from client control (Mods)
3. Partial bypass from client control (TXT/RP)

That would come in handy

**Comment by Filocava99** [comment]
The enhancement you suggested (https://github.com/Filocava99/CavaAntiCheat/issues/8) should work just fine for that issue too.

**Comment by BartosB13** [comment]
However, I'd like to add that it would be nice to have an option to bypass the user check altogether if:

1. Has the appropriate permission
2. He is a server operator (op)

This can be useful, e.g. at the very beginning of plugin configuration after its installation on the server in conjunction with the plugin reload option, if it exists.
